import { Status } from "../src/generated/prisma/enums";
import { ProjectModel } from "../src/generated/prisma/models";

export const listProjects: Omit<ProjectModel, 'projectId'>[] = [
    { status: Status.IN_DEVELOPMENT, imageLogo: '/projects/mazeMall.webp', title: 'Maze Mall', desc: 'Приключенческий шутер-рогалик, в котором вам предстоит найти выход из захваченного демоном лабиринта торгового центра.', link: 'https://vkplay.ru/play/game/maze_market', bgColor: '#665974', startOfDevelopment: new Date('2023-03-15'), endOfDevelopment: null, createdAt: new Date('2023-03-15'), updatedAt: new Date('2023-03-15') },
    { status: Status.COMPLETED, imageLogo: '/projects/profcom.webp', title: 'Сайт профкома УрГЭУ', desc: 'Многостраничная платформа для профсоюзной организации студентов УрГЭУ. Личный кабинет, оплата взносов и информационные разделы.', link: 'https://профкомургэу.рф', bgColor: '#596674', startOfDevelopment: new Date('2022-09-01'), endOfDevelopment: new Date('2023-06-30'), createdAt: new Date('2022-09-01'), updatedAt: new Date('2023-06-30') },
    { status: Status.IN_DEVELOPMENT, imageLogo: '/projects/catnBall.webp', title: 'CatnBall', desc: 'Платформер, где вы управляете котом, наклоняя телефон. Освойте ритм прыжков и используйте клубок, чтобы достичь цели!', link: 'https://rustore.ru/catalog/app/com.Amazengs.Catnball', bgColor: '#4e6788', startOfDevelopment: new Date('2024-01-10'), endOfDevelopment: null, createdAt: new Date('2024-01-10'), updatedAt: new Date('2024-01-10') },
    { status: Status.IN_DEVELOPMENT, imageLogo: '/projects/mazeMall.webp', title: 'Inside Out Me', desc: 'Визуальная новелла с необычным сюжетом: в антиутопичном будущем ученая Дешка работает над собственным проектом в стенах зловещей корпорации.', link: 'https://t.me/insideoutmeoff', bgColor: '#745959', startOfDevelopment: new Date('2024-06-01'), endOfDevelopment: null, createdAt: new Date('2024-06-01'), updatedAt: new Date('2024-06-01') },
    { status: Status.COMPLETED, imageLogo: '/projects/mazeMall.webp', title: 'UNIT Landing', desc: 'Одностраничный сайт студии с анимациями и адаптивной вёрсткой.', link: 'https://unit-studio.ru', bgColor: '#4a5d6b', startOfDevelopment: new Date('2023-01-20'), endOfDevelopment: new Date('2023-04-15'), createdAt: new Date('2023-01-20'), updatedAt: new Date('2023-04-15') },
    { status: Status.IN_DEVELOPMENT, imageLogo: '/projects/catnBall.webp', title: 'Cyber Runner', desc: 'Бесконечный раннер в киберпанк-сеттинге с процедурной генерацией уровней.', link: 'https://store.steampowered.com/app/cyber_runner', bgColor: '#3d4a5c', startOfDevelopment: new Date('2024-09-05'), endOfDevelopment: null, createdAt: new Date('2024-09-05'), updatedAt: new Date('2024-09-05') },
    { status: Status.COMPLETED, imageLogo: '/projects/profcom.webp', title: 'TaskFlow', desc: 'Веб-приложение для управления задачами с канбан-досками и командной работой.', link: 'https://taskflow.app', bgColor: '#5c6b4a', startOfDevelopment: new Date('2022-11-10'), endOfDevelopment: new Date('2023-08-20'), createdAt: new Date('2022-11-10'), updatedAt: new Date('2023-08-20') },
    { status: Status.IN_DEVELOPMENT, imageLogo: '/projects/catnBall.webp', title: 'Pixel Dungeon', desc: 'Классический рогалик с пиксельной графикой и глубокой системой крафта.', link: 'https://pixeldungeon.game', bgColor: '#6b4a5c', startOfDevelopment: new Date('2023-07-01'), endOfDevelopment: null, createdAt: new Date('2023-07-01'), updatedAt: new Date('2023-07-01') },
    { status: Status.COMPLETED, imageLogo: '/projects/profcom.webp', title: 'EcoTracker', desc: 'Мобильное приложение для отслеживания углеродного следа и эко-привычек.', link: 'https://ecotracker.app', bgColor: '#4a6b5c', startOfDevelopment: new Date('2023-02-14'), endOfDevelopment: new Date('2023-12-01'), createdAt: new Date('2023-02-14'), updatedAt: new Date('2023-12-01') },
    { status: Status.IN_DEVELOPMENT, imageLogo: '/projects/catnBall.webp', title: 'Space Trader', desc: 'Экономическая стратегия о торговле между звёздными системами.', link: 'https://spacetrader.io', bgColor: '#3d3d5c', startOfDevelopment: new Date('2025-01-15'), endOfDevelopment: null, createdAt: new Date('2025-01-15'), updatedAt: new Date('2025-01-15') },
    { status: Status.COMPLETED, imageLogo: '/projects/profcom.webp', title: 'RecipeBox', desc: 'Приложение для хранения рецептов с умным поиском по ингредиентам.', link: 'https://recipebox.app', bgColor: '#6b5c4a', startOfDevelopment: new Date('2022-05-20'), endOfDevelopment: new Date('2022-11-30'), createdAt: new Date('2022-05-20'), updatedAt: new Date('2022-11-30') },
    { status: Status.IN_DEVELOPMENT, imageLogo: '/projects/catnBall.webp', title: 'FitBuddy', desc: 'Трекер тренировок с персонализированными планами и статистикой прогресса.', link: 'https://fitbuddy.app', bgColor: '#4a5c6b', startOfDevelopment: new Date('2024-03-10'), endOfDevelopment: null, createdAt: new Date('2024-03-10'), updatedAt: new Date('2024-03-10') },
    { status: Status.COMPLETED, imageLogo: '/projects/profcom.webp', title: 'MindMap Pro', desc: 'Инструмент для создания ментальных карт с совместной работой в реальном времени.', link: 'https://mindmap.pro', bgColor: '#5c4a6b', startOfDevelopment: new Date('2023-04-05'), endOfDevelopment: new Date('2024-01-20'), createdAt: new Date('2023-04-05'), updatedAt: new Date('2024-01-20') },
    { status: Status.IN_DEVELOPMENT, imageLogo: '/projects/mazeMall.webp', title: 'GhostNotes', desc: 'Анонимный мессенджер с самоуничтожающимися сообщениями.', link: 'https://ghostnotes.app', bgColor: '#4a4a4a', startOfDevelopment: new Date('2024-10-01'), endOfDevelopment: null, createdAt: new Date('2024-10-01'), updatedAt: new Date('2024-10-01') },
    { status: Status.COMPLETED, imageLogo: '/projects/profcom.webp', title: 'CryptoWallet', desc: 'Безопасный кошелёк для хранения и обмена криптовалют с поддержкой 20+ сетей.', link: 'https://cryptowallet.io', bgColor: '#5c6b5c', startOfDevelopment: new Date('2022-07-15'), endOfDevelopment: new Date('2023-03-10'), createdAt: new Date('2022-07-15'), updatedAt: new Date('2023-03-10') },
    { status: Status.IN_DEVELOPMENT, imageLogo: '/projects/mazeMall.webp', title: 'AI Artist', desc: 'Генератор изображений на основе текстовых описаний с использованием нейросетей.', link: 'https://aiartist.app', bgColor: '#6b4a4a', startOfDevelopment: new Date('2025-02-01'), endOfDevelopment: null, createdAt: new Date('2025-02-01'), updatedAt: new Date('2025-02-01') },
    { status: Status.COMPLETED, imageLogo: '/projects/catnBall.webp', title: 'StudyHub', desc: 'Платформа для онлайн-обучения с видеоуроками, тестами и системой прогресса.', link: 'https://studyhub.ru', bgColor: '#4a5c4a', startOfDevelopment: new Date('2023-06-01'), endOfDevelopment: new Date('2024-02-28'), createdAt: new Date('2023-06-01'), updatedAt: new Date('2024-02-28') },
    { status: Status.IN_DEVELOPMENT, imageLogo: '/projects/mazeMall.webp', title: 'MusicLab', desc: 'Веб-студия для создания музыки с виртуальными инструментами и секвенсором.', link: 'https://musiclab.app', bgColor: '#5c4a5c', startOfDevelopment: new Date('2024-08-15'), endOfDevelopment: null, createdAt: new Date('2024-08-15'), updatedAt: new Date('2024-08-15') },
    { status: Status.COMPLETED, imageLogo: '/projects/catnBall.webp', title: 'PlantCare', desc: 'Приложение для ухода за комнатными растениями с напоминаниями и определением по фото.', link: 'https://plantcare.app', bgColor: '#4a6b4a', startOfDevelopment: new Date('2023-09-10'), endOfDevelopment: new Date('2024-05-01'), createdAt: new Date('2023-09-10'), updatedAt: new Date('2024-05-01') },
    { status: Status.IN_DEVELOPMENT, imageLogo: '/projects/catnBall.webp', title: 'CityBuilder', desc: 'Градостроительный симулятор с реалистичной экономикой и экологией.', link: 'https://citybuilder.game', bgColor: '#6b5c5c', startOfDevelopment: new Date('2025-04-01'), endOfDevelopment: null, createdAt: new Date('2025-04-01'), updatedAt: new Date('2025-04-01') },
]